---
apiVersion: v1
kind: ConfigMap
metadata:
  name: background-config
  labels:
    app: background
data:
  API_HOST: "api"
  API_PORT: "5002"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: background
  labels:
    app: background
spec:
  replicas: 1
  selector:
    matchLabels:
      app: background
  template:
    metadata:
      labels:
        app: background
    spec:
      containers:
      - name: background
        image: public.ecr.aws/cloudacademy-labs/cloudacademy/labs/k8s-assessment/background
        envFrom:
        - configMapRef:
            name: background-config

